version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - protogetter
    - reassign
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
  settings:
    dogsled:
      max-blank-identifiers: 3
    funlen:
      lines: 100
    gocognit:
      min-complexity: 20
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - atomicalign
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - findcall
        - framepointer
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shadow
        - shift
        - sigchanyzer
        - slog
        - sortslice
        - stdmethods
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite
      disable-all: true
    misspell:
      locale: US
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
