// Code generated by bpf2go; DO NOT EDIT.

package guard

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GuardCommKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type GuardInodeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

// LoadGuard returns the embedded CollectionSpec for Guard.
func LoadGuard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Guard: %w", err)
	}

	return spec, err
}

// LoadGuardObjects loads Guard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GuardObjects
//	*GuardPrograms
//	*GuardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGuardObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGuard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GuardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardSpecs struct {
	GuardProgramSpecs
	GuardMapSpecs
	GuardVariableSpecs
}

// GuardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardProgramSpecs struct {
	GuardFileOpen          *ebpf.ProgramSpec `ebpf:"guard_file_open"`
	GuardFilePermission    *ebpf.ProgramSpec `ebpf:"guard_file_permission"`
	GuardMmapFile          *ebpf.ProgramSpec `ebpf:"guard_mmap_file"`
	GuardPathLink          *ebpf.ProgramSpec `ebpf:"guard_path_link"`
	GuardPathMkdir         *ebpf.ProgramSpec `ebpf:"guard_path_mkdir"`
	GuardPathRename        *ebpf.ProgramSpec `ebpf:"guard_path_rename"`
	GuardPathSymlink       *ebpf.ProgramSpec `ebpf:"guard_path_symlink"`
	GuardPathUnlink        *ebpf.ProgramSpec `ebpf:"guard_path_unlink"`
	GuardPtraceAccessCheck *ebpf.ProgramSpec `ebpf:"guard_ptrace_access_check"`
	GuardSbMount           *ebpf.ProgramSpec `ebpf:"guard_sb_mount"`
	GuardTaskAlloc         *ebpf.ProgramSpec `ebpf:"guard_task_alloc"`
	GuardTaskFree          *ebpf.ProgramSpec `ebpf:"guard_task_free"`
}

// GuardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardMapSpecs struct {
	GuardComms       *ebpf.MapSpec `ebpf:"guard_comms"`
	GuardConfig      *ebpf.MapSpec `ebpf:"guard_config"`
	GuardExeInodes   *ebpf.MapSpec `ebpf:"guard_exe_inodes"`
	GuardFsDevices   *ebpf.MapSpec `ebpf:"guard_fs_devices"`
	GuardInodes      *ebpf.MapSpec `ebpf:"guard_inodes"`
	GuardPath        *ebpf.MapSpec `ebpf:"guard_path"`
	GuardTaintedPids *ebpf.MapSpec `ebpf:"guard_tainted_pids"`
	Rb               *ebpf.MapSpec `ebpf:"rb"`
	TmpBuf           *ebpf.MapSpec `ebpf:"tmp_buf"`
}

// GuardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardVariableSpecs struct {
}

// GuardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardObjects struct {
	GuardPrograms
	GuardMaps
	GuardVariables
}

func (o *GuardObjects) Close() error {
	return _GuardClose(
		&o.GuardPrograms,
		&o.GuardMaps,
	)
}

// GuardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardMaps struct {
	GuardComms       *ebpf.Map `ebpf:"guard_comms"`
	GuardConfig      *ebpf.Map `ebpf:"guard_config"`
	GuardExeInodes   *ebpf.Map `ebpf:"guard_exe_inodes"`
	GuardFsDevices   *ebpf.Map `ebpf:"guard_fs_devices"`
	GuardInodes      *ebpf.Map `ebpf:"guard_inodes"`
	GuardPath        *ebpf.Map `ebpf:"guard_path"`
	GuardTaintedPids *ebpf.Map `ebpf:"guard_tainted_pids"`
	Rb               *ebpf.Map `ebpf:"rb"`
	TmpBuf           *ebpf.Map `ebpf:"tmp_buf"`
}

func (m *GuardMaps) Close() error {
	return _GuardClose(
		m.GuardComms,
		m.GuardConfig,
		m.GuardExeInodes,
		m.GuardFsDevices,
		m.GuardInodes,
		m.GuardPath,
		m.GuardTaintedPids,
		m.Rb,
		m.TmpBuf,
	)
}

// GuardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardVariables struct {
}

// GuardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardPrograms struct {
	GuardFileOpen          *ebpf.Program `ebpf:"guard_file_open"`
	GuardFilePermission    *ebpf.Program `ebpf:"guard_file_permission"`
	GuardMmapFile          *ebpf.Program `ebpf:"guard_mmap_file"`
	GuardPathLink          *ebpf.Program `ebpf:"guard_path_link"`
	GuardPathMkdir         *ebpf.Program `ebpf:"guard_path_mkdir"`
	GuardPathRename        *ebpf.Program `ebpf:"guard_path_rename"`
	GuardPathSymlink       *ebpf.Program `ebpf:"guard_path_symlink"`
	GuardPathUnlink        *ebpf.Program `ebpf:"guard_path_unlink"`
	GuardPtraceAccessCheck *ebpf.Program `ebpf:"guard_ptrace_access_check"`
	GuardSbMount           *ebpf.Program `ebpf:"guard_sb_mount"`
	GuardTaskAlloc         *ebpf.Program `ebpf:"guard_task_alloc"`
	GuardTaskFree          *ebpf.Program `ebpf:"guard_task_free"`
}

func (p *GuardPrograms) Close() error {
	return _GuardClose(
		p.GuardFileOpen,
		p.GuardFilePermission,
		p.GuardMmapFile,
		p.GuardPathLink,
		p.GuardPathMkdir,
		p.GuardPathRename,
		p.GuardPathSymlink,
		p.GuardPathUnlink,
		p.GuardPtraceAccessCheck,
		p.GuardSbMount,
		p.GuardTaskAlloc,
		p.GuardTaskFree,
	)
}

func _GuardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/guard_bpf.o
var _GuardBytes []byte
