// Code generated by bpf2go; DO NOT EDIT.

package guard

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GuardInodeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	GuardMapGuardConfig             = "guard_config"
	GuardMapGuardExeActions         = "guard_exe_actions"
	GuardMapGuardExeEvents          = "guard_exe_events"
	GuardMapGuardFsDevices          = "guard_fs_devices"
	GuardMapGuardFsSbdevs           = "guard_fs_sbdevs"
	GuardMapGuardInodes             = "guard_inodes"
	GuardMapGuardPath               = "guard_path"
	GuardMapGuardTaintedPids        = "guard_tainted_pids"
	GuardMapRb                      = "rb"
	GuardMapTmpBuf                  = "tmp_buf"
	GuardProgGuardFileOpen          = "guard_file_open"
	GuardProgGuardFilePermission    = "guard_file_permission"
	GuardProgGuardFileTruncate      = "guard_file_truncate"
	GuardProgGuardInodeGetattr      = "guard_inode_getattr"
	GuardProgGuardInodePermission   = "guard_inode_permission"
	GuardProgGuardInodeReadlink     = "guard_inode_readlink"
	GuardProgGuardInodeRemovexattr  = "guard_inode_removexattr"
	GuardProgGuardInodeSetattr      = "guard_inode_setattr"
	GuardProgGuardInodeSetxattr     = "guard_inode_setxattr"
	GuardProgGuardMmapFile          = "guard_mmap_file"
	GuardProgGuardPathLink          = "guard_path_link"
	GuardProgGuardPathMkdir         = "guard_path_mkdir"
	GuardProgGuardPathMknod         = "guard_path_mknod"
	GuardProgGuardPathRename        = "guard_path_rename"
	GuardProgGuardPathRmdir         = "guard_path_rmdir"
	GuardProgGuardPathSymlink       = "guard_path_symlink"
	GuardProgGuardPathTruncate      = "guard_path_truncate"
	GuardProgGuardPathUnlink        = "guard_path_unlink"
	GuardProgGuardPtraceAccessCheck = "guard_ptrace_access_check"
	GuardProgGuardSbMount           = "guard_sb_mount"
	GuardProgGuardTaskAlloc         = "guard_task_alloc"
	GuardProgGuardTaskFree          = "guard_task_free"
)

// LoadGuard returns the embedded CollectionSpec for Guard.
func LoadGuard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Guard: %w", err)
	}

	return spec, err
}

// LoadGuardObjects loads Guard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GuardObjects
//	*GuardPrograms
//	*GuardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGuardObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGuard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GuardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardSpecs struct {
	GuardProgramSpecs
	GuardMapSpecs
	GuardVariableSpecs
}

// GuardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardProgramSpecs struct {
	GuardFileOpen          *ebpf.ProgramSpec `ebpf:"guard_file_open"`
	GuardFilePermission    *ebpf.ProgramSpec `ebpf:"guard_file_permission"`
	GuardFileTruncate      *ebpf.ProgramSpec `ebpf:"guard_file_truncate"`
	GuardInodeGetattr      *ebpf.ProgramSpec `ebpf:"guard_inode_getattr"`
	GuardInodePermission   *ebpf.ProgramSpec `ebpf:"guard_inode_permission"`
	GuardInodeReadlink     *ebpf.ProgramSpec `ebpf:"guard_inode_readlink"`
	GuardInodeRemovexattr  *ebpf.ProgramSpec `ebpf:"guard_inode_removexattr"`
	GuardInodeSetattr      *ebpf.ProgramSpec `ebpf:"guard_inode_setattr"`
	GuardInodeSetxattr     *ebpf.ProgramSpec `ebpf:"guard_inode_setxattr"`
	GuardMmapFile          *ebpf.ProgramSpec `ebpf:"guard_mmap_file"`
	GuardPathLink          *ebpf.ProgramSpec `ebpf:"guard_path_link"`
	GuardPathMkdir         *ebpf.ProgramSpec `ebpf:"guard_path_mkdir"`
	GuardPathMknod         *ebpf.ProgramSpec `ebpf:"guard_path_mknod"`
	GuardPathRename        *ebpf.ProgramSpec `ebpf:"guard_path_rename"`
	GuardPathRmdir         *ebpf.ProgramSpec `ebpf:"guard_path_rmdir"`
	GuardPathSymlink       *ebpf.ProgramSpec `ebpf:"guard_path_symlink"`
	GuardPathTruncate      *ebpf.ProgramSpec `ebpf:"guard_path_truncate"`
	GuardPathUnlink        *ebpf.ProgramSpec `ebpf:"guard_path_unlink"`
	GuardPtraceAccessCheck *ebpf.ProgramSpec `ebpf:"guard_ptrace_access_check"`
	GuardSbMount           *ebpf.ProgramSpec `ebpf:"guard_sb_mount"`
	GuardTaskAlloc         *ebpf.ProgramSpec `ebpf:"guard_task_alloc"`
	GuardTaskFree          *ebpf.ProgramSpec `ebpf:"guard_task_free"`
}

// GuardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardMapSpecs struct {
	GuardConfig      *ebpf.MapSpec `ebpf:"guard_config"`
	GuardExeActions  *ebpf.MapSpec `ebpf:"guard_exe_actions"`
	GuardExeEvents   *ebpf.MapSpec `ebpf:"guard_exe_events"`
	GuardFsDevices   *ebpf.MapSpec `ebpf:"guard_fs_devices"`
	GuardFsSbdevs    *ebpf.MapSpec `ebpf:"guard_fs_sbdevs"`
	GuardInodes      *ebpf.MapSpec `ebpf:"guard_inodes"`
	GuardPath        *ebpf.MapSpec `ebpf:"guard_path"`
	GuardTaintedPids *ebpf.MapSpec `ebpf:"guard_tainted_pids"`
	Rb               *ebpf.MapSpec `ebpf:"rb"`
	TmpBuf           *ebpf.MapSpec `ebpf:"tmp_buf"`
}

// GuardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardVariableSpecs struct {
}

// GuardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardObjects struct {
	GuardPrograms
	GuardMaps
	GuardVariables
}

func (o *GuardObjects) Close() error {
	return _GuardClose(
		&o.GuardPrograms,
		&o.GuardMaps,
	)
}

// GuardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardMaps struct {
	GuardConfig      *ebpf.Map `ebpf:"guard_config"`
	GuardExeActions  *ebpf.Map `ebpf:"guard_exe_actions"`
	GuardExeEvents   *ebpf.Map `ebpf:"guard_exe_events"`
	GuardFsDevices   *ebpf.Map `ebpf:"guard_fs_devices"`
	GuardFsSbdevs    *ebpf.Map `ebpf:"guard_fs_sbdevs"`
	GuardInodes      *ebpf.Map `ebpf:"guard_inodes"`
	GuardPath        *ebpf.Map `ebpf:"guard_path"`
	GuardTaintedPids *ebpf.Map `ebpf:"guard_tainted_pids"`
	Rb               *ebpf.Map `ebpf:"rb"`
	TmpBuf           *ebpf.Map `ebpf:"tmp_buf"`
}

func (m *GuardMaps) Close() error {
	return _GuardClose(
		m.GuardConfig,
		m.GuardExeActions,
		m.GuardExeEvents,
		m.GuardFsDevices,
		m.GuardFsSbdevs,
		m.GuardInodes,
		m.GuardPath,
		m.GuardTaintedPids,
		m.Rb,
		m.TmpBuf,
	)
}

// GuardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardVariables struct {
}

// GuardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGuardObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardPrograms struct {
	GuardFileOpen          *ebpf.Program `ebpf:"guard_file_open"`
	GuardFilePermission    *ebpf.Program `ebpf:"guard_file_permission"`
	GuardFileTruncate      *ebpf.Program `ebpf:"guard_file_truncate"`
	GuardInodeGetattr      *ebpf.Program `ebpf:"guard_inode_getattr"`
	GuardInodePermission   *ebpf.Program `ebpf:"guard_inode_permission"`
	GuardInodeReadlink     *ebpf.Program `ebpf:"guard_inode_readlink"`
	GuardInodeRemovexattr  *ebpf.Program `ebpf:"guard_inode_removexattr"`
	GuardInodeSetattr      *ebpf.Program `ebpf:"guard_inode_setattr"`
	GuardInodeSetxattr     *ebpf.Program `ebpf:"guard_inode_setxattr"`
	GuardMmapFile          *ebpf.Program `ebpf:"guard_mmap_file"`
	GuardPathLink          *ebpf.Program `ebpf:"guard_path_link"`
	GuardPathMkdir         *ebpf.Program `ebpf:"guard_path_mkdir"`
	GuardPathMknod         *ebpf.Program `ebpf:"guard_path_mknod"`
	GuardPathRename        *ebpf.Program `ebpf:"guard_path_rename"`
	GuardPathRmdir         *ebpf.Program `ebpf:"guard_path_rmdir"`
	GuardPathSymlink       *ebpf.Program `ebpf:"guard_path_symlink"`
	GuardPathTruncate      *ebpf.Program `ebpf:"guard_path_truncate"`
	GuardPathUnlink        *ebpf.Program `ebpf:"guard_path_unlink"`
	GuardPtraceAccessCheck *ebpf.Program `ebpf:"guard_ptrace_access_check"`
	GuardSbMount           *ebpf.Program `ebpf:"guard_sb_mount"`
	GuardTaskAlloc         *ebpf.Program `ebpf:"guard_task_alloc"`
	GuardTaskFree          *ebpf.Program `ebpf:"guard_task_free"`
}

func (p *GuardPrograms) Close() error {
	return _GuardClose(
		p.GuardFileOpen,
		p.GuardFilePermission,
		p.GuardFileTruncate,
		p.GuardInodeGetattr,
		p.GuardInodePermission,
		p.GuardInodeReadlink,
		p.GuardInodeRemovexattr,
		p.GuardInodeSetattr,
		p.GuardInodeSetxattr,
		p.GuardMmapFile,
		p.GuardPathLink,
		p.GuardPathMkdir,
		p.GuardPathMknod,
		p.GuardPathRename,
		p.GuardPathRmdir,
		p.GuardPathSymlink,
		p.GuardPathTruncate,
		p.GuardPathUnlink,
		p.GuardPtraceAccessCheck,
		p.GuardSbMount,
		p.GuardTaskAlloc,
		p.GuardTaskFree,
	)
}

func _GuardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/guard_bpf.o
var _GuardBytes []byte
