// Code generated by bpf2go; DO NOT EDIT.

package networkmonitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type NetMonCommKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type NetMonInodeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	NetMonMapRb                  = "rb"
	NetMonMapWatchComms          = "watch_comms"
	NetMonMapWatchExeInodes      = "watch_exe_inodes"
	NetMonProgTraceAccept        = "trace_accept"
	NetMonProgTraceAccept4       = "trace_accept4"
	NetMonProgTraceBind          = "trace_bind"
	NetMonProgTraceClose         = "trace_close"
	NetMonProgTraceConnect       = "trace_connect"
	NetMonProgTraceInetCskAccept = "trace_inet_csk_accept"
	NetMonProgTraceListen        = "trace_listen"
	NetMonProgTraceRecvfrom      = "trace_recvfrom"
	NetMonProgTraceRecvmsg       = "trace_recvmsg"
	NetMonProgTraceSendmsg       = "trace_sendmsg"
	NetMonProgTraceSendto        = "trace_sendto"
)

// LoadNetMon returns the embedded CollectionSpec for NetMon.
func LoadNetMon() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_NetMonBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load NetMon: %w", err)
	}

	return spec, err
}

// LoadNetMonObjects loads NetMon and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*NetMonObjects
//	*NetMonPrograms
//	*NetMonMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadNetMonObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadNetMon()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// NetMonSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMonSpecs struct {
	NetMonProgramSpecs
	NetMonMapSpecs
	NetMonVariableSpecs
}

// NetMonProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMonProgramSpecs struct {
	TraceAccept        *ebpf.ProgramSpec `ebpf:"trace_accept"`
	TraceAccept4       *ebpf.ProgramSpec `ebpf:"trace_accept4"`
	TraceBind          *ebpf.ProgramSpec `ebpf:"trace_bind"`
	TraceClose         *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceConnect       *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceInetCskAccept *ebpf.ProgramSpec `ebpf:"trace_inet_csk_accept"`
	TraceListen        *ebpf.ProgramSpec `ebpf:"trace_listen"`
	TraceRecvfrom      *ebpf.ProgramSpec `ebpf:"trace_recvfrom"`
	TraceRecvmsg       *ebpf.ProgramSpec `ebpf:"trace_recvmsg"`
	TraceSendmsg       *ebpf.ProgramSpec `ebpf:"trace_sendmsg"`
	TraceSendto        *ebpf.ProgramSpec `ebpf:"trace_sendto"`
}

// NetMonMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMonMapSpecs struct {
	Rb             *ebpf.MapSpec `ebpf:"rb"`
	WatchComms     *ebpf.MapSpec `ebpf:"watch_comms"`
	WatchExeInodes *ebpf.MapSpec `ebpf:"watch_exe_inodes"`
}

// NetMonVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type NetMonVariableSpecs struct {
}

// NetMonObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadNetMonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMonObjects struct {
	NetMonPrograms
	NetMonMaps
	NetMonVariables
}

func (o *NetMonObjects) Close() error {
	return _NetMonClose(
		&o.NetMonPrograms,
		&o.NetMonMaps,
	)
}

// NetMonMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadNetMonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMonMaps struct {
	Rb             *ebpf.Map `ebpf:"rb"`
	WatchComms     *ebpf.Map `ebpf:"watch_comms"`
	WatchExeInodes *ebpf.Map `ebpf:"watch_exe_inodes"`
}

func (m *NetMonMaps) Close() error {
	return _NetMonClose(
		m.Rb,
		m.WatchComms,
		m.WatchExeInodes,
	)
}

// NetMonVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadNetMonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMonVariables struct {
}

// NetMonPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadNetMonObjects or ebpf.CollectionSpec.LoadAndAssign.
type NetMonPrograms struct {
	TraceAccept        *ebpf.Program `ebpf:"trace_accept"`
	TraceAccept4       *ebpf.Program `ebpf:"trace_accept4"`
	TraceBind          *ebpf.Program `ebpf:"trace_bind"`
	TraceClose         *ebpf.Program `ebpf:"trace_close"`
	TraceConnect       *ebpf.Program `ebpf:"trace_connect"`
	TraceInetCskAccept *ebpf.Program `ebpf:"trace_inet_csk_accept"`
	TraceListen        *ebpf.Program `ebpf:"trace_listen"`
	TraceRecvfrom      *ebpf.Program `ebpf:"trace_recvfrom"`
	TraceRecvmsg       *ebpf.Program `ebpf:"trace_recvmsg"`
	TraceSendmsg       *ebpf.Program `ebpf:"trace_sendmsg"`
	TraceSendto        *ebpf.Program `ebpf:"trace_sendto"`
}

func (p *NetMonPrograms) Close() error {
	return _NetMonClose(
		p.TraceAccept,
		p.TraceAccept4,
		p.TraceBind,
		p.TraceClose,
		p.TraceConnect,
		p.TraceInetCskAccept,
		p.TraceListen,
		p.TraceRecvfrom,
		p.TraceRecvmsg,
		p.TraceSendmsg,
		p.TraceSendto,
	)
}

func _NetMonClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/networkmonitor_bpf.o
var _NetMonBytes []byte
