// Code generated by bpf2go; DO NOT EDIT.

package networkguard

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type GuardNetInodeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type GuardNetThrottleKey struct {
	_    structs.HostLayout
	Type uint32
	Comm [16]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	GuardNetMapGuardNetConfig         = "guard_net_config"
	GuardNetMapGuardNetEvents         = "guard_net_events"
	GuardNetMapGuardNetExeActions     = "guard_net_exe_actions"
	GuardNetMapGuardNetRb             = "guard_net_rb"
	GuardNetMapGuardNetThrottle       = "guard_net_throttle"
	GuardNetProgGuardNetSocketBind    = "guard_net_socket_bind"
	GuardNetProgGuardNetSocketConnect = "guard_net_socket_connect"
	GuardNetProgGuardNetSocketListen  = "guard_net_socket_listen"
	GuardNetProgGuardNetSocketRecvmsg = "guard_net_socket_recvmsg"
	GuardNetProgGuardNetSocketSendmsg = "guard_net_socket_sendmsg"
)

// LoadGuardNet returns the embedded CollectionSpec for GuardNet.
func LoadGuardNet() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GuardNetBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load GuardNet: %w", err)
	}

	return spec, err
}

// LoadGuardNetObjects loads GuardNet and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*GuardNetObjects
//	*GuardNetPrograms
//	*GuardNetMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadGuardNetObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadGuardNet()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// GuardNetSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardNetSpecs struct {
	GuardNetProgramSpecs
	GuardNetMapSpecs
	GuardNetVariableSpecs
}

// GuardNetProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardNetProgramSpecs struct {
	GuardNetSocketBind    *ebpf.ProgramSpec `ebpf:"guard_net_socket_bind"`
	GuardNetSocketConnect *ebpf.ProgramSpec `ebpf:"guard_net_socket_connect"`
	GuardNetSocketListen  *ebpf.ProgramSpec `ebpf:"guard_net_socket_listen"`
	GuardNetSocketRecvmsg *ebpf.ProgramSpec `ebpf:"guard_net_socket_recvmsg"`
	GuardNetSocketSendmsg *ebpf.ProgramSpec `ebpf:"guard_net_socket_sendmsg"`
}

// GuardNetMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardNetMapSpecs struct {
	GuardNetConfig     *ebpf.MapSpec `ebpf:"guard_net_config"`
	GuardNetEvents     *ebpf.MapSpec `ebpf:"guard_net_events"`
	GuardNetExeActions *ebpf.MapSpec `ebpf:"guard_net_exe_actions"`
	GuardNetRb         *ebpf.MapSpec `ebpf:"guard_net_rb"`
	GuardNetThrottle   *ebpf.MapSpec `ebpf:"guard_net_throttle"`
}

// GuardNetVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type GuardNetVariableSpecs struct {
}

// GuardNetObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadGuardNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardNetObjects struct {
	GuardNetPrograms
	GuardNetMaps
	GuardNetVariables
}

func (o *GuardNetObjects) Close() error {
	return _GuardNetClose(
		&o.GuardNetPrograms,
		&o.GuardNetMaps,
	)
}

// GuardNetMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadGuardNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardNetMaps struct {
	GuardNetConfig     *ebpf.Map `ebpf:"guard_net_config"`
	GuardNetEvents     *ebpf.Map `ebpf:"guard_net_events"`
	GuardNetExeActions *ebpf.Map `ebpf:"guard_net_exe_actions"`
	GuardNetRb         *ebpf.Map `ebpf:"guard_net_rb"`
	GuardNetThrottle   *ebpf.Map `ebpf:"guard_net_throttle"`
}

func (m *GuardNetMaps) Close() error {
	return _GuardNetClose(
		m.GuardNetConfig,
		m.GuardNetEvents,
		m.GuardNetExeActions,
		m.GuardNetRb,
		m.GuardNetThrottle,
	)
}

// GuardNetVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadGuardNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardNetVariables struct {
}

// GuardNetPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadGuardNetObjects or ebpf.CollectionSpec.LoadAndAssign.
type GuardNetPrograms struct {
	GuardNetSocketBind    *ebpf.Program `ebpf:"guard_net_socket_bind"`
	GuardNetSocketConnect *ebpf.Program `ebpf:"guard_net_socket_connect"`
	GuardNetSocketListen  *ebpf.Program `ebpf:"guard_net_socket_listen"`
	GuardNetSocketRecvmsg *ebpf.Program `ebpf:"guard_net_socket_recvmsg"`
	GuardNetSocketSendmsg *ebpf.Program `ebpf:"guard_net_socket_sendmsg"`
}

func (p *GuardNetPrograms) Close() error {
	return _GuardNetClose(
		p.GuardNetSocketBind,
		p.GuardNetSocketConnect,
		p.GuardNetSocketListen,
		p.GuardNetSocketRecvmsg,
		p.GuardNetSocketSendmsg,
	)
}

func _GuardNetClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/guardnet_bpf.o
var _GuardNetBytes []byte
