package daemon

import (
	"os"
	"sync"
	"time"

	log "github.com/sirupsen/logrus"

	"github.com/Virgula0/app-listener/cmd/functions/editprotected"
	"github.com/Virgula0/app-listener/internal/fscrypt"
	"github.com/Virgula0/app-listener/internal/guard"
	ebpf "github.com/Virgula0/app-listener/internal/infrastructure"
	"github.com/Virgula0/app-listener/internal/usecase"
)

// selfProtectSpec is one always-on guard over the daemon's own on-disk state.
type selfProtectSpec struct {
	path string
	mode guard.Mode
}

// selfProtectSpecs are the guards the daemon attaches over its own state,
// independent of any [watch] section:
//
//	/etc/app-listener              ModeReadOnly — every process may read it
//	                               (daemon.conf stays world-readable), but only
//	                               the app-listener binary may modify anything
//	                               in it (write / rename / unlink / chmod / …)
//	/etc/app-listener/fscrypt.key  ModeWhitelist, empty list — not even
//	                               readable except by the app-listener binary
//	/etc/app-listener/edit-auth.hash  ModeWhitelist, empty list — the
//	                               edit-protected password hash, sealed the
//	                               same way as the fscrypt key so a root
//	                               process that is not the app-listener binary
//	                               cannot read it to mount an offline crack
//	                               nor overwrite it to install its own
//	                               password
//
// The key / hash guards stack on top of the directory guard: the RO guard
// would allow the read, the whitelist-empty guard denies it, and
// any-deny-wins across stacked LSM programs keeps it sealed.
func selfProtectSpecs() []selfProtectSpec {
	return []selfProtectSpec{
		{selfProtectDir, guard.ModeReadOnly},
		{fscrypt.MasterKeyFile, guard.ModeWhitelist},
		{editprotected.HashFile, guard.ModeWhitelist},
	}
}

// selfSweepEvery is the inode-refresh interval for the self guards — it
// catches an fscrypt.key regenerated by `app-listener daemon --genkey` while
// the daemon runs (a new inode the single-file key guard would otherwise
// stop tracking). Matches the usecase's own sweep cadence.
const selfSweepEvery = 30 * time.Second

// selfGuards holds the always-on guards over the daemon's own on-disk state.
//
// They are deliberately NOT part of the usecase's guard set. On SIGHUP the
// config guards transiently double — the new batch attaches before the old
// one detaches, so protection is never dropped — and that peak count is
// bounded by the kernel's per-LSM-hook program limit (BPF_MAX_TRAMP_LINKS,
// 38). Self guards step aside for the reload: detach() before, attach()
// after, so they never count against that window. The /etc/app-listener
// protection gap lasts only the reload (an admin-triggered operation).
//
// A self guard that cannot attach — LSM slot exhaustion on a very large
// config, or any other reason — is logged and skipped: the daemon's
// config-driven protection is the core function and must never be blocked
// by this add-on.
type selfGuards struct {
	events chan usecase.DaemonEvent

	mu      sync.Mutex
	guards  []*guard.Guard
	stops   []chan struct{}
	stopped bool // detach() called; a concurrent attach() must bail
}

func newSelfGuards() *selfGuards {
	return &selfGuards{events: make(chan usecase.DaemonEvent, 256)}
}

// ensureHashFilePlaceholder makes sure editprotected.HashFile exists (even
// zero-length) before self-guards attach. Two things make this necessary:
//
//   - The per-file guard for it is only created when the file ALREADY
//     exists at attach time (the os.Stat gate in the loop below) — so a
//     fresh install where no password has ever been set gets no dedicated
//     guard for it at all.
//   - Once the /etc/app-listener ReadOnly guard IS attached, its self-allow
//     covers rewriting an EXISTING directory entry but not creating a new
//     one — so WriteHashFile's old create-temp-then-rename dance got denied
//     the moment the daemon (which is itself the actor) was already running
//     and guarding its own directory.
//
// Creating an empty placeholder here, before any guard exists, sidesteps
// both: from then on the file always exists, so its own dedicated
// ModeWhitelist guard (self-allow, maskless = every event, unaffected by
// the ReadOnly restriction above) is what WriteHashFile's in-place rewrite
// goes through. A zero-length file is the documented "no password
// configured" state (editprotected.HashFileExists / LoadHashFile treat
// empty the same as absent). A no-op when /etc/app-listener itself does not
// exist yet (no install has run) or the file is already there.
func ensureHashFilePlaceholder() error {
	if _, err := os.Stat(editprotected.HashFile); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	if _, statErr := os.Stat(selfProtectDir); statErr != nil {
		return nil //nolint:nilerr // no /etc/app-listener yet (nothing installed): nothing to bootstrap, not an error for the caller
	}
	f, err := os.OpenFile(editprotected.HashFile, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		if os.IsExist(err) {
			return nil
		}
		return err
	}
	return f.Close()
}

// Events is the merged denial stream from every attached self guard, tagged
// with the resource path (e.g. resource=/etc/app-listener). Never closed.
func (s *selfGuards) Events() <-chan usecase.DaemonEvent { return s.events }

// attach builds and starts the self-protection guards, pinned under pin.gen.
// Safe to run in its own goroutine: a detach() that races it wins (attach
// stops whatever it had already built and returns). Best effort — a guard
// that fails to build/start is logged and skipped; a spec path that does not
// exist (working-dir config, no system install) is skipped silently.
func (s *selfGuards) attach(pin pinCfg) {
	s.mu.Lock()
	s.stopped = false
	s.mu.Unlock()

	// Bootstrap the edit-auth hash file BEFORE any guard attaches (see
	// ensureHashFilePlaceholder): once the /etc/app-listener ReadOnly guard
	// below is live, creating a brand-new directory entry inside it is no
	// longer possible for the self binary — only rewriting an EXISTING one
	// is. Best-effort like the rest of self-protection; a failure here just
	// means WriteHashFile falls back to its own create-if-missing path.
	if err := ensureHashFilePlaceholder(); err != nil {
		log.Warnf("daemon: self-protection: could not pre-create %s (%v) — setting an edit-protected password while the daemon runs may fail until it does", editprotected.HashFile, err)
	}

	self, err := ebpf.ComputeBinaryEntry("/proc/self/exe")
	if err != nil {
		log.Errorf("daemon: self-protection disabled: cannot resolve own executable (%v) — /etc/app-listener is NOT self-guarded", err)
		return
	}

	for _, spec := range selfProtectSpecs() {
		s.mu.Lock()
		bail := s.stopped
		s.mu.Unlock()
		if bail {
			return
		}
		if _, statErr := os.Stat(spec.path); statErr != nil {
			continue
		}
		g, gErr := guard.NewGuard(spec.path, spec.mode, nil, true, 0,
			guard.WithEagerPopulate(),
			// The daemon's own binary, uid-0 gated, every event: install /
			// --genkey / --update-catalog-only write these paths.
			guard.WithSelfAllowBinary(self, nil),
			// Do NOT widen the raw block-device gate to the rootfs device.
			guard.WithBackingDevices(nil),
			guard.WithPinning(pin.prefix("self:"+spec.path)))
		if gErr != nil {
			log.Errorf("daemon: self-protection: %s is NOT guarded (%v) — the daemon runs normally, config protection is unaffected", spec.path, gErr)
			continue
		}
		if startErr := g.Start(); startErr != nil {
			log.Errorf("daemon: self-protection: %s guard attached but its reader failed to start (%v) — detaching", spec.path, startErr)
			g.Stop()
			continue
		}
		stop := make(chan struct{})

		s.mu.Lock()
		if s.stopped {
			s.mu.Unlock()
			close(stop)
			g.Stop()
			return
		}
		s.guards = append(s.guards, g)
		s.stops = append(s.stops, stop)
		s.mu.Unlock()

		go s.forward(spec.path, g, stop)
		log.Infof("daemon: self-protection: guarding %s", spec.path)
	}
}

// detach stops every self guard and its forwarder, and makes any in-flight
// attach() bail. Idempotent.
func (s *selfGuards) detach() {
	s.mu.Lock()
	s.stopped = true
	guards, stops := s.guards, s.stops
	s.guards, s.stops = nil, nil
	s.mu.Unlock()

	for _, stop := range stops {
		close(stop)
	}
	for _, g := range guards {
		g.Stop()
	}
}

// forward tags one self guard's events with its resource path and merges
// them into s.events. Self guards carry no whitelist and no fscrypt
// lifecycle, so there is no binary re-sync; only a light inode sweep runs,
// to pick up a regenerated fscrypt.key.
func (s *selfGuards) forward(resource string, g *guard.Guard, stop <-chan struct{}) {
	sweep := time.NewTicker(selfSweepEvery)
	defer sweep.Stop()
	for {
		select {
		case ev, ok := <-g.Events():
			if !ok {
				return
			}
			select {
			case s.events <- usecase.DaemonEvent{Resource: resource, Event: ev}:
			case <-stop:
				return
			}
		case <-sweep.C:
			if err := g.SweepInodes(); err != nil {
				log.Warnf("daemon: self-protection: inode sweep for %s: %v", resource, err)
			}
		case <-stop:
			return
		}
	}
}

// mergeDaemonEvents fans the usecase stream and the self-protection stream
// into one channel for the run loops. Neither input is ever closed, so the
// forwarding goroutines live for the daemon process lifetime.
func mergeDaemonEvents(srcs ...<-chan usecase.DaemonEvent) <-chan usecase.DaemonEvent {
	out := make(chan usecase.DaemonEvent, 512)
	for _, src := range srcs {
		go func(c <-chan usecase.DaemonEvent) {
			for ev := range c {
				out <- ev
			}
		}(src)
	}
	return out
}
