// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadMonitor returns the embedded CollectionSpec for Monitor.
func LoadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Monitor: %w", err)
	}

	return spec, err
}

// LoadMonitorObjects loads Monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MonitorObjects
//	*MonitorPrograms
//	*MonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorSpecs struct {
	MonitorProgramSpecs
	MonitorMapSpecs
	MonitorVariableSpecs
}

// MonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorProgramSpecs struct {
	TraceDoSysOpen    *ebpf.ProgramSpec `ebpf:"trace_do_sys_open"`
	TraceDoSysOpenat2 *ebpf.ProgramSpec `ebpf:"trace_do_sys_openat2"`
	TraceKsysRead     *ebpf.ProgramSpec `ebpf:"trace_ksys_read"`
	TraceKsysWrite    *ebpf.ProgramSpec `ebpf:"trace_ksys_write"`
	TraceLinkat       *ebpf.ProgramSpec `ebpf:"trace_linkat"`
	TraceMkdirat      *ebpf.ProgramSpec `ebpf:"trace_mkdirat"`
	TraceRenameat2    *ebpf.ProgramSpec `ebpf:"trace_renameat2"`
	TraceSymlinkat    *ebpf.ProgramSpec `ebpf:"trace_symlinkat"`
	TraceUnlinkat     *ebpf.ProgramSpec `ebpf:"trace_unlinkat"`
}

// MonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorMapSpecs struct {
	Rb *ebpf.MapSpec `ebpf:"rb"`
}

// MonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorVariableSpecs struct {
}

// MonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorObjects struct {
	MonitorPrograms
	MonitorMaps
	MonitorVariables
}

func (o *MonitorObjects) Close() error {
	return _MonitorClose(
		&o.MonitorPrograms,
		&o.MonitorMaps,
	)
}

// MonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorMaps struct {
	Rb *ebpf.Map `ebpf:"rb"`
}

func (m *MonitorMaps) Close() error {
	return _MonitorClose(
		m.Rb,
	)
}

// MonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorVariables struct {
}

// MonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorPrograms struct {
	TraceDoSysOpen    *ebpf.Program `ebpf:"trace_do_sys_open"`
	TraceDoSysOpenat2 *ebpf.Program `ebpf:"trace_do_sys_openat2"`
	TraceKsysRead     *ebpf.Program `ebpf:"trace_ksys_read"`
	TraceKsysWrite    *ebpf.Program `ebpf:"trace_ksys_write"`
	TraceLinkat       *ebpf.Program `ebpf:"trace_linkat"`
	TraceMkdirat      *ebpf.Program `ebpf:"trace_mkdirat"`
	TraceRenameat2    *ebpf.Program `ebpf:"trace_renameat2"`
	TraceSymlinkat    *ebpf.Program `ebpf:"trace_symlinkat"`
	TraceUnlinkat     *ebpf.Program `ebpf:"trace_unlinkat"`
}

func (p *MonitorPrograms) Close() error {
	return _MonitorClose(
		p.TraceDoSysOpen,
		p.TraceDoSysOpenat2,
		p.TraceKsysRead,
		p.TraceKsysWrite,
		p.TraceLinkat,
		p.TraceMkdirat,
		p.TraceRenameat2,
		p.TraceSymlinkat,
		p.TraceUnlinkat,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/monitor_bpf.o
var _MonitorBytes []byte
