package install

import (
	"fmt"
	"strings"
)

// Section is one [watch <path>] block of the generated config.
type Section struct {
	Path    string
	Allow   []BinaryRule // whitelisted binaries and their event restrictions
	Encrypt bool
}

// GenerateConf renders the daemon configuration for the given sections.
// The output is a valid daemon.conf: every section carries a whitelist and
// an explicit need_encryption directive. A binary with a non-empty event
// list is emitted as "<path> EV1,EV2", restricting it to those events; a
// binary with an empty list is allowed every event and emitted as a bare
// path.
func GenerateConf(sections []Section) string {
	var b strings.Builder
	b.WriteString("# Generated by `app-listener install`.\n")
	b.WriteString("#\n")
	b.WriteString("# Each [watch <path>] section protects the path: only the\n")
	b.WriteString("# binaries listed below may access it, everything else is\n")
	b.WriteString("# denied (EPERM). Identity is verified by inode, not name.\n")
	b.WriteString("#\n")
	b.WriteString("# Edit freely, then save. See daemon-samples/daemon.conf\n")
	b.WriteString("# for the full syntax documentation.\n")
	for _, s := range sections {
		b.WriteString("\n[watch ")
		b.WriteString(s.Path)
		b.WriteString("]\n\n")
		for _, bin := range s.Allow {
			b.WriteString(bin.Path)
			if len(bin.Events) > 0 {
				b.WriteString(" ")
				b.WriteString(strings.Join(bin.Events, ","))
			}
			b.WriteString("\n")
		}
		if len(s.Allow) == 0 {
			b.WriteString("# no binaries whitelisted: every access is denied\n")
		}
		b.WriteString("\n")
		if s.Encrypt {
			b.WriteString("need_encryption: true\n")
		} else {
			b.WriteString("need_encryption: false\n")
		}
	}
	return b.String()
}

// SetNeedEncryption updates the need_encryption directive of the [watch
// path] section inside confText, inserting the directive right after the
// section header when it is absent. Everything else in the file — comments,
// whitelists, event restrictions, section order — is preserved verbatim so
// manual edits made in the embedded editor survive.
func SetNeedEncryption(confText, path string, value bool) (string, error) {
	directive := "need_encryption: false"
	if value {
		directive = "need_encryption: true"
	}

	lines := strings.Split(confText, "\n")
	header := "[watch " + path + "]"
	start := findSectionStart(lines, header)
	if start == -1 {
		return "", fmt.Errorf("section %q not found in configuration", header)
	}
	end := findSectionEnd(lines, start)
	replaced := false
	for i := start + 1; i < end; i++ {
		if strings.HasPrefix(strings.TrimSpace(lines[i]), "need_encryption:") {
			lines[i] = keepIndent(lines[i], directive)
			replaced = true
			break
		}
	}
	if !replaced {
		insertAt := firstContentLine(lines, start+1, end)
		lines = append(lines, "")
		copy(lines[insertAt+1:], lines[insertAt:])
		lines[insertAt] = directive
	}
	return strings.Join(lines, "\n"), nil
}

// findSectionStart returns the index of the exact [watch ...] header line,
// or -1.
func findSectionStart(lines []string, header string) int {
	for i, line := range lines {
		if strings.TrimSpace(line) == header {
			return i
		}
	}
	return -1
}

// findSectionEnd returns the index of the first line of the next section
// (or len(lines) for the last one).
func findSectionEnd(lines []string, start int) int {
	for i := start + 1; i < len(lines); i++ {
		if strings.HasPrefix(strings.TrimSpace(lines[i]), "[watch ") {
			return i
		}
	}
	return len(lines)
}

// firstContentLine returns the first non-empty, non-comment line in
// [start, end), or end when the section is empty.
func firstContentLine(lines []string, start, end int) int {
	for i := start; i < end; i++ {
		t := strings.TrimSpace(lines[i])
		if t != "" && !strings.HasPrefix(t, "#") {
			return i
		}
	}
	return end
}

// keepIndent replaces the content of line keeping its leading whitespace.
func keepIndent(line, replacement string) string {
	return strings.Repeat(" ", len(line)-len(strings.TrimLeft(line, " \t"))) + replacement
}
