package install

import (
	"fmt"
	"strings"
)

// Section is one [watch <path>] block of the generated config.
type Section struct {
	Path    string
	Allow   []BinaryRule // whitelisted binaries and their event restrictions
	Encrypt bool
	// Libs are extra allowed libraries for this section's binaries, emitted as
	// `allow_lib <path>` directives (see CandidateDir.Libs).
	Libs []string
	// LibDirs are library directories guarded read-only for this section's
	// binaries, emitted as `lib_dir <path>` directives (see
	// CandidateDir.LibDirRelPaths).
	LibDirs []string
	// ExtraWatchPaths optionally turns the section into an encryption GROUP:
	// the section path stays the fscrypt root (its need_encryption governs
	// the group) while each extra path becomes its own guarded tree sharing
	// the section's whitelist, emitted as `watch: <path>` directives. Used
	// for self-updating applications whose update workspace must stay
	// outside the guarded set (e.g. Discord's versioned app dirs).
	ExtraWatchPaths []string
}

// GenerateConf renders the daemon configuration for the given sections.
// The output is a valid daemon.conf: every section carries a whitelist and
// an explicit need_encryption directive. A binary with a non-empty event
// list is emitted as "<path> EV1,EV2", restricting it to those events; a
// binary with an empty list is allowed every event and emitted as a bare
// path.
func GenerateConf(sections []Section) string {
	var b strings.Builder
	b.WriteString("# Generated by `app-listener install`.\n")
	b.WriteString("#\n")
	b.WriteString("# Each [watch <path>] section protects the path: only the\n")
	b.WriteString("# binaries listed below may access it, everything else is\n")
	b.WriteString("# denied (EPERM). Identity is verified by inode, not name.\n")
	b.WriteString("#\n")
	b.WriteString("# A section may also carry `watch: <path>` directives: the section\n")
	b.WriteString("# path is then the ENCRYPTION root only, and each watched path is a\n")
	b.WriteString("# separate guarded tree sharing the section whitelist (for\n")
	b.WriteString("# self-updating apps whose updater writes the vault root).\n")
	b.WriteString("#\n")
	b.WriteString("# Edit freely, then save. See daemon-samples/daemon.conf\n")
	b.WriteString("# for the full syntax documentation.\n")
	b.WriteString(GenerateSections(sections))
	return b.String()
}

// GenerateSections renders just the [watch ...] blocks, with no file header,
// each block preceded by a blank line. Used to append new sections to an
// existing daemon.conf (install --diff-catalog) without disturbing what is
// already there. Every generated path (section root, `watch:` directives,
// whitelisted binaries) is double-quoted: catalog paths regularly contain
// spaces (e.g. Steam/Proton's "Proton - Experimental"), and quoting is the
// only form the daemon config parser accepts for those unambiguously.
func GenerateSections(sections []Section) string {
	var b strings.Builder
	for _, s := range sections {
		b.WriteString("\n[watch ")
		b.WriteString(quotePath(s.Path))
		b.WriteString("]\n\n")
		for _, w := range s.ExtraWatchPaths {
			b.WriteString("watch: ")
			b.WriteString(quotePath(w))
			b.WriteString("\n")
		}
		if len(s.ExtraWatchPaths) > 0 {
			b.WriteString("\n")
		}
		for _, bin := range s.Allow {
			b.WriteString(quotePath(bin.Path))
			if len(bin.Events) > 0 {
				b.WriteString(" ")
				b.WriteString(strings.Join(bin.Events, ","))
			}
			b.WriteString("\n")
		}
		if len(s.Allow) == 0 {
			b.WriteString("# no binaries whitelisted: every access is denied\n")
		}
		for _, lib := range s.Libs {
			b.WriteString("allow_lib ")
			b.WriteString(quotePath(lib))
			b.WriteString("\n")
		}
		for _, dir := range s.LibDirs {
			b.WriteString("lib_dir ")
			b.WriteString(quotePath(dir))
			b.WriteString("\n")
		}
		b.WriteString("\n")
		if s.Encrypt {
			b.WriteString("need_encryption: true\n")
		} else {
			b.WriteString("need_encryption: false\n")
		}
	}
	return b.String()
}

// SetNeedEncryption updates the need_encryption directive of the [watch
// path] section inside confText, inserting the directive right after the
// section header when it is absent. Everything else in the file — comments,
// whitelists, event restrictions, section order — is preserved verbatim so
// manual edits made in the embedded editor survive.
func SetNeedEncryption(confText, path string, value bool) (string, error) {
	directive := "need_encryption: false"
	if value {
		directive = "need_encryption: true"
	}

	lines := strings.Split(confText, "\n")
	start := findSectionStart(lines, path)
	if start == -1 {
		return "", fmt.Errorf("section for %q not found in configuration", path)
	}
	end := findSectionEnd(lines, start)
	replaced := false
	for i := start + 1; i < end; i++ {
		if strings.HasPrefix(strings.TrimSpace(lines[i]), "need_encryption:") {
			lines[i] = keepIndent(lines[i], directive)
			replaced = true
			break
		}
	}
	if !replaced {
		insertAt := firstContentLine(lines, start+1, end)
		lines = append(lines, "")
		copy(lines[insertAt+1:], lines[insertAt:])
		lines[insertAt] = directive
	}
	return strings.Join(lines, "\n"), nil
}

// SetSectionWhitelist replaces the binary rule lines within the [watch path]
// section of confText with newRules. It preserves the section header,
// blank lines, comments (#), need_encryption: directives, and leading
// whitespace on every preserved line. Binary rule lines are any non-empty,
// non-comment, non-directive lines in the section body.
func SetSectionWhitelist(confText, path string, newRules []BinaryRule) (string, error) {
	lines := strings.Split(confText, "\n")
	start := findSectionStart(lines, path)
	if start == -1 {
		return "", fmt.Errorf("section for %q not found in configuration", path)
	}
	end := findSectionEnd(lines, start)

	// Collect the WHITELIST-entry lines only: `watch:` directives (grouped
	// sections) and `path =` placeholders are group STRUCTURE — replacing
	// them would silently unwatch the grouped trees on every refresh.
	var binaryIndices []int
	for i := start + 1; i < end; i++ {
		t := strings.TrimSpace(lines[i])
		if t == "" || strings.HasPrefix(t, "#") || strings.HasPrefix(t, "need_encryption:") ||
			isWatchDirectiveText(t) || isPathDirectiveText(t) || isLibDirectiveText(t) {
			continue
		}
		binaryIndices = append(binaryIndices, i)
	}

	newLines := make([]string, 0, len(newRules))
	for _, rule := range newRules {
		line := quotePath(rule.Path)
		if len(rule.Events) > 0 {
			line += " " + strings.Join(rule.Events, ",")
		}
		newLines = append(newLines, line)
	}

	indent := ""
	if len(binaryIndices) > 0 {
		indent = keepIndent(lines[binaryIndices[0]], "")
	}
	for i := range newLines {
		newLines[i] = indent + newLines[i]
	}

	var prefix, suffix []string
	if len(binaryIndices) > 0 {
		prefix = lines[:binaryIndices[0]]
		suffix = lines[binaryIndices[len(binaryIndices)-1]+1:]
	} else {
		insertAt := firstContentLine(lines, start+1, end)
		prefix = lines[:insertAt]
		suffix = lines[insertAt:]
	}

	result := make([]string, 0, len(prefix)+len(newLines)+len(suffix))
	result = append(result, prefix...)
	result = append(result, newLines...)
	result = append(result, suffix...)
	return strings.Join(result, "\n"), nil
}

// isWatchDirectiveText recognizes a `watch: <path>` group-structure line
// (trimmed) inside a section body.
func isWatchDirectiveText(t string) bool {
	return strings.HasPrefix(t, "watch:") || strings.HasPrefix(t, "watch ")
}

// isLibDirectiveText recognizes the library-trust directives `allow_lib
// <path>` and `lib_dir <path>` (trimmed) inside a section body. They are
// section STRUCTURE, not whitelist entries: SetSectionWhitelist must leave
// them alone or a catalog refresh would silently strip an app's library
// permissions and break it (or, worse, drop the write-protection that makes
// those libraries trustworthy).
func isLibDirectiveText(t string) bool {
	for _, d := range [...]string{"allow_lib", "lib_dir"} {
		rest, ok := strings.CutPrefix(t, d)
		if ok && rest != "" && (rest[0] == ' ' || rest[0] == '\t' || rest[0] == ':') {
			return true
		}
	}
	return false
}

// isPathDirectiveText recognizes the TUI placeholder `path = <dir>` line.
func isPathDirectiveText(t string) bool {
	return strings.HasPrefix(t, "path = ") || t == "path ="
}

// findSectionStart returns the index of the "[watch <path>]" header line
// whose path — quoted or not — equals path, or -1.
func findSectionStart(lines []string, path string) int {
	for i, line := range lines {
		if headerPath, ok := ParseSectionHeaderPath(line); ok && headerPath == path {
			return i
		}
	}
	return -1
}

// ParseSectionHeaderPath extracts the path from a "[watch <path>]" section
// header line (leading/trailing whitespace ignored), unquoting a
// double-quoted path; ok is false for anything that is not a section header.
// Exported so callers outside this package (e.g. the live re-scan safety
// check in cmd/functions/install) can match a section header regardless of
// whether it was written quoted or bare.
func ParseSectionHeaderPath(line string) (path string, ok bool) {
	t := strings.TrimSpace(line)
	if !strings.HasPrefix(t, "[watch ") || !strings.HasSuffix(t, "]") {
		return "", false
	}
	return unquotePath(strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(t, "[watch "), "]"))), true
}

// quotePath wraps path in double quotes: the installer always quotes the
// paths it generates (section roots, `watch:` directives, whitelisted
// binaries) so a path containing spaces or other whitespace round-trips
// through the daemon config parser unambiguously; quoting is optional there
// only for hand-written configs.
func quotePath(path string) string {
	return `"` + path + `"`
}

// unquotePath strips a surrounding pair of double quotes from s, if present.
func unquotePath(s string) string {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

// findSectionEnd returns the index of the first line of the next section
// (or len(lines) for the last one).
func findSectionEnd(lines []string, start int) int {
	for i := start + 1; i < len(lines); i++ {
		if strings.HasPrefix(strings.TrimSpace(lines[i]), "[watch ") {
			return i
		}
	}
	return len(lines)
}

// firstContentLine returns the first non-empty, non-comment line in
// [start, end), or end when the section is empty.
func firstContentLine(lines []string, start, end int) int {
	for i := start; i < end; i++ {
		t := strings.TrimSpace(lines[i])
		if t != "" && !strings.HasPrefix(t, "#") {
			return i
		}
	}
	return end
}

// keepIndent replaces the content of line keeping its leading whitespace.
func keepIndent(line, replacement string) string {
	return strings.Repeat(" ", len(line)-len(strings.TrimLeft(line, " \t"))) + replacement
}
