// Code generated by bpf2go; DO NOT EDIT.

package monitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadMonitor returns the embedded CollectionSpec for Monitor.
func LoadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Monitor: %w", err)
	}

	return spec, err
}

// LoadMonitorObjects loads Monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MonitorObjects
//	*MonitorPrograms
//	*MonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMonitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorSpecs struct {
	MonitorProgramSpecs
	MonitorMapSpecs
	MonitorVariableSpecs
}

// MonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorProgramSpecs struct {
	TraceDoSendfile       *ebpf.ProgramSpec `ebpf:"trace_do_sendfile"`
	TraceDoSplice         *ebpf.ProgramSpec `ebpf:"trace_do_splice"`
	TraceDoSpliceDirect   *ebpf.ProgramSpec `ebpf:"trace_do_splice_direct"`
	TraceMmap             *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceSecurityMmapFile *ebpf.ProgramSpec `ebpf:"trace_security_mmap_file"`
	TraceSpliceFileRange  *ebpf.ProgramSpec `ebpf:"trace_splice_file_range"`
	TraceVfsCopyFileRange *ebpf.ProgramSpec `ebpf:"trace_vfs_copy_file_range"`
	TraceVfsIterRead      *ebpf.ProgramSpec `ebpf:"trace_vfs_iter_read"`
	TraceVfsLink          *ebpf.ProgramSpec `ebpf:"trace_vfs_link"`
	TraceVfsMkdir         *ebpf.ProgramSpec `ebpf:"trace_vfs_mkdir"`
	TraceVfsOpen          *ebpf.ProgramSpec `ebpf:"trace_vfs_open"`
	TraceVfsRead          *ebpf.ProgramSpec `ebpf:"trace_vfs_read"`
	TraceVfsReadv         *ebpf.ProgramSpec `ebpf:"trace_vfs_readv"`
	TraceVfsRename        *ebpf.ProgramSpec `ebpf:"trace_vfs_rename"`
	TraceVfsRmdir         *ebpf.ProgramSpec `ebpf:"trace_vfs_rmdir"`
	TraceVfsSymlink       *ebpf.ProgramSpec `ebpf:"trace_vfs_symlink"`
	TraceVfsUnlink        *ebpf.ProgramSpec `ebpf:"trace_vfs_unlink"`
	TraceVfsWrite         *ebpf.ProgramSpec `ebpf:"trace_vfs_write"`
}

// MonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorMapSpecs struct {
	Rb     *ebpf.MapSpec `ebpf:"rb"`
	TmpBuf *ebpf.MapSpec `ebpf:"tmp_buf"`
}

// MonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorVariableSpecs struct {
}

// MonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorObjects struct {
	MonitorPrograms
	MonitorMaps
	MonitorVariables
}

func (o *MonitorObjects) Close() error {
	return _MonitorClose(
		&o.MonitorPrograms,
		&o.MonitorMaps,
	)
}

// MonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorMaps struct {
	Rb     *ebpf.Map `ebpf:"rb"`
	TmpBuf *ebpf.Map `ebpf:"tmp_buf"`
}

func (m *MonitorMaps) Close() error {
	return _MonitorClose(
		m.Rb,
		m.TmpBuf,
	)
}

// MonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorVariables struct {
}

// MonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorPrograms struct {
	TraceDoSendfile       *ebpf.Program `ebpf:"trace_do_sendfile"`
	TraceDoSplice         *ebpf.Program `ebpf:"trace_do_splice"`
	TraceDoSpliceDirect   *ebpf.Program `ebpf:"trace_do_splice_direct"`
	TraceMmap             *ebpf.Program `ebpf:"trace_mmap"`
	TraceSecurityMmapFile *ebpf.Program `ebpf:"trace_security_mmap_file"`
	TraceSpliceFileRange  *ebpf.Program `ebpf:"trace_splice_file_range"`
	TraceVfsCopyFileRange *ebpf.Program `ebpf:"trace_vfs_copy_file_range"`
	TraceVfsIterRead      *ebpf.Program `ebpf:"trace_vfs_iter_read"`
	TraceVfsLink          *ebpf.Program `ebpf:"trace_vfs_link"`
	TraceVfsMkdir         *ebpf.Program `ebpf:"trace_vfs_mkdir"`
	TraceVfsOpen          *ebpf.Program `ebpf:"trace_vfs_open"`
	TraceVfsRead          *ebpf.Program `ebpf:"trace_vfs_read"`
	TraceVfsReadv         *ebpf.Program `ebpf:"trace_vfs_readv"`
	TraceVfsRename        *ebpf.Program `ebpf:"trace_vfs_rename"`
	TraceVfsRmdir         *ebpf.Program `ebpf:"trace_vfs_rmdir"`
	TraceVfsSymlink       *ebpf.Program `ebpf:"trace_vfs_symlink"`
	TraceVfsUnlink        *ebpf.Program `ebpf:"trace_vfs_unlink"`
	TraceVfsWrite         *ebpf.Program `ebpf:"trace_vfs_write"`
}

func (p *MonitorPrograms) Close() error {
	return _MonitorClose(
		p.TraceDoSendfile,
		p.TraceDoSplice,
		p.TraceDoSpliceDirect,
		p.TraceMmap,
		p.TraceSecurityMmapFile,
		p.TraceSpliceFileRange,
		p.TraceVfsCopyFileRange,
		p.TraceVfsIterRead,
		p.TraceVfsLink,
		p.TraceVfsMkdir,
		p.TraceVfsOpen,
		p.TraceVfsRead,
		p.TraceVfsReadv,
		p.TraceVfsRename,
		p.TraceVfsRmdir,
		p.TraceVfsSymlink,
		p.TraceVfsUnlink,
		p.TraceVfsWrite,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/monitor_bpf.o
var _MonitorBytes []byte
