// Code generated by bpf2go; DO NOT EDIT.

package monitor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	MonitorMapRb                     = "rb"
	MonitorMapTmpBuf                 = "tmp_buf"
	MonitorProgTraceDoFaccessat      = "trace_do_faccessat"
	MonitorProgTraceDoSendfile       = "trace_do_sendfile"
	MonitorProgTraceDoSplice         = "trace_do_splice"
	MonitorProgTraceDoSpliceDirect   = "trace_do_splice_direct"
	MonitorProgTraceMmap             = "trace_mmap"
	MonitorProgTraceNotifyChange     = "trace_notify_change"
	MonitorProgTraceSecurityMmapFile = "trace_security_mmap_file"
	MonitorProgTraceSpliceFileRange  = "trace_splice_file_range"
	MonitorProgTraceVfsCopyFileRange = "trace_vfs_copy_file_range"
	MonitorProgTraceVfsGetattr       = "trace_vfs_getattr"
	MonitorProgTraceVfsIterRead      = "trace_vfs_iter_read"
	MonitorProgTraceVfsLink          = "trace_vfs_link"
	MonitorProgTraceVfsMkdir         = "trace_vfs_mkdir"
	MonitorProgTraceVfsMknod         = "trace_vfs_mknod"
	MonitorProgTraceVfsOpen          = "trace_vfs_open"
	MonitorProgTraceVfsRead          = "trace_vfs_read"
	MonitorProgTraceVfsReadlink      = "trace_vfs_readlink"
	MonitorProgTraceVfsReadv         = "trace_vfs_readv"
	MonitorProgTraceVfsRemovexattr   = "trace_vfs_removexattr"
	MonitorProgTraceVfsRename        = "trace_vfs_rename"
	MonitorProgTraceVfsRmdir         = "trace_vfs_rmdir"
	MonitorProgTraceVfsSetxattr      = "trace_vfs_setxattr"
	MonitorProgTraceVfsSymlink       = "trace_vfs_symlink"
	MonitorProgTraceVfsUnlink        = "trace_vfs_unlink"
	MonitorProgTraceVfsWrite         = "trace_vfs_write"
)

// LoadMonitor returns the embedded CollectionSpec for Monitor.
func LoadMonitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MonitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Monitor: %w", err)
	}

	return spec, err
}

// LoadMonitorObjects loads Monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MonitorObjects
//	*MonitorPrograms
//	*MonitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMonitorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMonitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MonitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorSpecs struct {
	MonitorProgramSpecs
	MonitorMapSpecs
	MonitorVariableSpecs
}

// MonitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorProgramSpecs struct {
	TraceDoFaccessat      *ebpf.ProgramSpec `ebpf:"trace_do_faccessat"`
	TraceDoSendfile       *ebpf.ProgramSpec `ebpf:"trace_do_sendfile"`
	TraceDoSplice         *ebpf.ProgramSpec `ebpf:"trace_do_splice"`
	TraceDoSpliceDirect   *ebpf.ProgramSpec `ebpf:"trace_do_splice_direct"`
	TraceMmap             *ebpf.ProgramSpec `ebpf:"trace_mmap"`
	TraceNotifyChange     *ebpf.ProgramSpec `ebpf:"trace_notify_change"`
	TraceSecurityMmapFile *ebpf.ProgramSpec `ebpf:"trace_security_mmap_file"`
	TraceSpliceFileRange  *ebpf.ProgramSpec `ebpf:"trace_splice_file_range"`
	TraceVfsCopyFileRange *ebpf.ProgramSpec `ebpf:"trace_vfs_copy_file_range"`
	TraceVfsGetattr       *ebpf.ProgramSpec `ebpf:"trace_vfs_getattr"`
	TraceVfsIterRead      *ebpf.ProgramSpec `ebpf:"trace_vfs_iter_read"`
	TraceVfsLink          *ebpf.ProgramSpec `ebpf:"trace_vfs_link"`
	TraceVfsMkdir         *ebpf.ProgramSpec `ebpf:"trace_vfs_mkdir"`
	TraceVfsMknod         *ebpf.ProgramSpec `ebpf:"trace_vfs_mknod"`
	TraceVfsOpen          *ebpf.ProgramSpec `ebpf:"trace_vfs_open"`
	TraceVfsRead          *ebpf.ProgramSpec `ebpf:"trace_vfs_read"`
	TraceVfsReadlink      *ebpf.ProgramSpec `ebpf:"trace_vfs_readlink"`
	TraceVfsReadv         *ebpf.ProgramSpec `ebpf:"trace_vfs_readv"`
	TraceVfsRemovexattr   *ebpf.ProgramSpec `ebpf:"trace_vfs_removexattr"`
	TraceVfsRename        *ebpf.ProgramSpec `ebpf:"trace_vfs_rename"`
	TraceVfsRmdir         *ebpf.ProgramSpec `ebpf:"trace_vfs_rmdir"`
	TraceVfsSetxattr      *ebpf.ProgramSpec `ebpf:"trace_vfs_setxattr"`
	TraceVfsSymlink       *ebpf.ProgramSpec `ebpf:"trace_vfs_symlink"`
	TraceVfsUnlink        *ebpf.ProgramSpec `ebpf:"trace_vfs_unlink"`
	TraceVfsWrite         *ebpf.ProgramSpec `ebpf:"trace_vfs_write"`
}

// MonitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorMapSpecs struct {
	Rb     *ebpf.MapSpec `ebpf:"rb"`
	TmpBuf *ebpf.MapSpec `ebpf:"tmp_buf"`
}

// MonitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MonitorVariableSpecs struct {
}

// MonitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorObjects struct {
	MonitorPrograms
	MonitorMaps
	MonitorVariables
}

func (o *MonitorObjects) Close() error {
	return _MonitorClose(
		&o.MonitorPrograms,
		&o.MonitorMaps,
	)
}

// MonitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorMaps struct {
	Rb     *ebpf.Map `ebpf:"rb"`
	TmpBuf *ebpf.Map `ebpf:"tmp_buf"`
}

func (m *MonitorMaps) Close() error {
	return _MonitorClose(
		m.Rb,
		m.TmpBuf,
	)
}

// MonitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorVariables struct {
}

// MonitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMonitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type MonitorPrograms struct {
	TraceDoFaccessat      *ebpf.Program `ebpf:"trace_do_faccessat"`
	TraceDoSendfile       *ebpf.Program `ebpf:"trace_do_sendfile"`
	TraceDoSplice         *ebpf.Program `ebpf:"trace_do_splice"`
	TraceDoSpliceDirect   *ebpf.Program `ebpf:"trace_do_splice_direct"`
	TraceMmap             *ebpf.Program `ebpf:"trace_mmap"`
	TraceNotifyChange     *ebpf.Program `ebpf:"trace_notify_change"`
	TraceSecurityMmapFile *ebpf.Program `ebpf:"trace_security_mmap_file"`
	TraceSpliceFileRange  *ebpf.Program `ebpf:"trace_splice_file_range"`
	TraceVfsCopyFileRange *ebpf.Program `ebpf:"trace_vfs_copy_file_range"`
	TraceVfsGetattr       *ebpf.Program `ebpf:"trace_vfs_getattr"`
	TraceVfsIterRead      *ebpf.Program `ebpf:"trace_vfs_iter_read"`
	TraceVfsLink          *ebpf.Program `ebpf:"trace_vfs_link"`
	TraceVfsMkdir         *ebpf.Program `ebpf:"trace_vfs_mkdir"`
	TraceVfsMknod         *ebpf.Program `ebpf:"trace_vfs_mknod"`
	TraceVfsOpen          *ebpf.Program `ebpf:"trace_vfs_open"`
	TraceVfsRead          *ebpf.Program `ebpf:"trace_vfs_read"`
	TraceVfsReadlink      *ebpf.Program `ebpf:"trace_vfs_readlink"`
	TraceVfsReadv         *ebpf.Program `ebpf:"trace_vfs_readv"`
	TraceVfsRemovexattr   *ebpf.Program `ebpf:"trace_vfs_removexattr"`
	TraceVfsRename        *ebpf.Program `ebpf:"trace_vfs_rename"`
	TraceVfsRmdir         *ebpf.Program `ebpf:"trace_vfs_rmdir"`
	TraceVfsSetxattr      *ebpf.Program `ebpf:"trace_vfs_setxattr"`
	TraceVfsSymlink       *ebpf.Program `ebpf:"trace_vfs_symlink"`
	TraceVfsUnlink        *ebpf.Program `ebpf:"trace_vfs_unlink"`
	TraceVfsWrite         *ebpf.Program `ebpf:"trace_vfs_write"`
}

func (p *MonitorPrograms) Close() error {
	return _MonitorClose(
		p.TraceDoFaccessat,
		p.TraceDoSendfile,
		p.TraceDoSplice,
		p.TraceDoSpliceDirect,
		p.TraceMmap,
		p.TraceNotifyChange,
		p.TraceSecurityMmapFile,
		p.TraceSpliceFileRange,
		p.TraceVfsCopyFileRange,
		p.TraceVfsGetattr,
		p.TraceVfsIterRead,
		p.TraceVfsLink,
		p.TraceVfsMkdir,
		p.TraceVfsMknod,
		p.TraceVfsOpen,
		p.TraceVfsRead,
		p.TraceVfsReadlink,
		p.TraceVfsReadv,
		p.TraceVfsRemovexattr,
		p.TraceVfsRename,
		p.TraceVfsRmdir,
		p.TraceVfsSetxattr,
		p.TraceVfsSymlink,
		p.TraceVfsUnlink,
		p.TraceVfsWrite,
	)
}

func _MonitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed embeds/monitor_bpf.o
var _MonitorBytes []byte
